version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: toms-gym-backend
    ports:
      - "9888:8080"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - USE_MOCK_DB=false
      - DB_INSTANCE=toms-gym:us-east1:my-db
      - DB_USER=postgres
      - DB_PASS=test
      - DB_NAME=postgres
      - GCS_BUCKET_NAME=jtr-lift-u-4ever-cool-bucket
      - GOOGLE_APPLICATION_CREDENTIALS=/credentials/credentials.json
      - GOOGLE_CLOUD_PROJECT=toms-gym
      - PORT=8080
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    volumes:
      - ./Backend:/app
      - ./Backend/credentials.json:/credentials/credentials.json:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  frontend:
    build:
      context: ./my-frontend
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:9888
    container_name: toms-gym-frontend
    ports:
      - "9081:80"
    environment:
      - VITE_API_URL=http://localhost:9888
      - VITE_BUILD_TIMESTAMP=development
      - PORT=80
    depends_on:
      - backend
    restart: unless-stopped

  test-server:
    image: nginx:alpine
    container_name: toms-gym-test-server
    ports:
      - "8002:80"
    volumes:
      - ./tests:/usr/share/nginx/html
      - ./tests/html:/usr/share/nginx/html/html
    restart: unless-stopped

networks:
  default:
    name: toms-gym-network 