version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - DB_INSTANCE=${DB_INSTANCE}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - GCS_BUCKET_NAME=${GCS_BUCKET_NAME}
    volumes:
      - ./:/app
      - ${GOOGLE_APPLICATION_CREDENTIALS}:/app/credentials.json:ro
    restart: unless-stopped 