version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:8080"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - DB_INSTANCE=toms-gym:us-east1:my-db
      - DB_USER=postgres
      - DB_PASS=test
      - DB_NAME=postgres
      - GCS_BUCKET_NAME=your-bucket-name
    volumes:
      - ./:/app
      - ./credentials.json:/app/credentials.json:ro
    restart: unless-stopped

  test:
    build: .
    command: pytest -v
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials.json
      - DB_INSTANCE=toms-gym:us-east1:my-db
      - DB_USER=postgres
      - DB_PASS=test
      - DB_NAME=postgres
      - GCS_BUCKET_NAME=your-bucket-name
      - PYTHONPATH=/app
    volumes:
      - ./:/app
      - ./credentials.json:/app/credentials.json:ro

volumes:
  postgres_data: 