steps:
  - name: 'node:18-alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        npm ci --no-audit --prefer-offline && npm run build

  # Set up docker-container builder (required for cache export)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        docker buildx create --name mybuilder --driver docker-container --use
        docker buildx inspect --bootstrap

  # Build and push with caching (now using docker-container driver)
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'docker'
    args:
      - 'buildx'
      - 'build'
      - '--platform=linux/amd64'
      - '-t'
      - 'gcr.io/toms-gym/my-frontend:latest'
      - '--cache-from=type=registry,ref=gcr.io/toms-gym/my-frontend:cache'
      - '--cache-to=type=registry,ref=gcr.io/toms-gym/my-frontend:cache,mode=max'
      - '--push'
      - '.'

